name: Question
description: Ask a question or get help with the project.
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: What would you like to know?
      description: A clear and concise description of what you're asking.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any other context that might help us answer your question.
